 
export interface IJob {
    id: string, 
    title: string,
    jobCode: string, 
    status: string,
    reason: string, 
    workingTime: string, 
    notes: [],
    aboutOurCompany: [],
    benefit: [],
    domain: [], 
    interviewProcess: [], 
    jobDescription: [],
    languages: [],
    level: [], 
    location: [],
    salaryRange?: [], 
    salary: string, 
    postDate: string, 
}